Repository VilhelmPrytz/utbildningsmaterial, pull requests merged in 2019-11, with the labels that each got.

#1 Fixade stavfel och förtydligade vissa förklaringar.
  content/docs/svenska-2/litteraturhistoria-och-berattarteknik.md
Labels: småfel, stavfel

#5 Stavfel
  content/docs/historia-1a1/upplysningstiden.md
Labels: stavfel

#6 Skrev till på begreppslistan.
  content/docs/kemi-1/atomer-haller-ihop.md
Labels: nytt innehåll
